apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: pokemondb
        - name: MYSQL_USER
          value: foo
        - name: MYSQL_PASSWORD
          value: Secret123
        - name: MYSQL_ROOT_PASSWORD
          value: Secret123
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: Secret123
        ports:
        - containerPort: 3306
          name: mysql
