apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-deployment
  labels:
    app: pokemon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokemon
  template:
    metadata:
      labels:
        app: pokemon
    spec:
      containers:
      - name: pokemon
        image: mojofrank/mypokemonj
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: foo
        - name: DB_PASS
          value: Secret123
        - name: DB_NAME
          value: pokemondb
---
apiVersion: v1
kind: Service
metadata:
  name: pokemone-svc
spec:
  type: NodePort
  selector:
    app: pokemon
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
